### Write a function so that the columns of the output matrix are powers of the input vector.

In [12]:
import numpy as np

In [13]:
def matrix():    
    x = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
    N = 3
    increasing = True
    print(np.vander(x,N,increasing))
matrix()

[[    1     3     9]
 [    1     5    25]
 [    1     7    49]
 [    1     2     4]
 [    1     8    64]
 [    1    10   100]
 [    1    11   121]
 [    1    65  4225]
 [    1    72  5184]
 [    1    81  6561]
 [    1    99  9801]
 [    1   100 10000]
 [    1   150 22500]]


### Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [39]:
def moving_avg(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
my_list = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
print(moving_avg(my_list,n=3))

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
